version: "3"

services:
    redis-server:
      image: redis:latest
      container_name: redis-server
    fapi:
      image: python:3.9
      build: .
      container_name: fastapi-backend
      command: >
        sh -c "pip install poetry &&
               poetry install &&
               poetry run uvicorn --host=0.0.0.0 --port=8000 --reload main:app"
      working_dir: /usr/src
      depends_on:
        - redis-server
      volumes:
        - ./:/usr/src
      ports:
       - "8000:8000"