name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    steps:
    - name: Create and start virtual environment
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv


    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version}}

    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag my-image-name:myapp

    - name: Run Docker Image
      run: docker run -d --name myapp -p 3000:300 my-image-name:myapp

    - name: Logs for Docker Image
      run: docker logs $(docker ps -aq)

    - name: Pytest
      run: |
        virtualenv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install pytest poetry
        poetry install
        python -m pytest


