name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag my-image-name:myapp

    - name: Run Docker Image
      run: docker run -d --name myapp -p 3000:300 my-image-name:myapp

    - name: Logs for Docker Image
      run: docker logs $(docker ps -aq)

    - name: Pytest
      run: python -m pytest
